### ISSUE TITLE
Getting a `corfu-popup-info-mode` error 

### ISSUE THREAD

**Issue by CGenie** [SystemCrafters/crafted-emacs#255] opened 2022-12-01 08:43 UTC
Hello,

Recently I started getting this error:

```
Symbol's function definition is void: corfu-popupinfo-mode
```

I see it's in the `corfu` extension and it was added recently in commit 773adbe3f0fb195167abf2c045613be6c20c94db. I use the `straight` package manager. I'm not sure how to fix this?

**Comment by jeffbowman** [comment] 2022-12-01 16:48
Well, that depends.  If you are using `straight` directly, you can use something like: 

`(use-package :straight (:files (:defaults "extensions/*"))`

or the solution presented in #254 

or wait a bit while I review and merge that PR.

**Comment by jeffbowman** [comment] 2022-12-01 16:52
Closing this as a duplicate of #252, which is resolved with #254.

**Closed by jeffbowman** 2022-12-01 16:52 UTC
